FROM archlinux:latest

RUN sed -i '/NoExtract/d' /etc/pacman.conf && \
    pacman -Syu --noconfirm && \
    pacman -Sy --noconfirm \
        doxygen \
        git && \
    pacman -Scc --noconfirm

WORKDIR /docs

COPY docs/cpp/Doxyfile Doxyfile

CMD ["sh", "-c", "echo 'Usage: docker run --rm -v $(pwd):/docs docs-builder <command>'; echo '  doxygen Doxyfile'"]
