#!/bin/bash

PROJECT_NAME=$1
if [ -z "$PROJECT_NAME" ]; then
  echo "Использование: new-project <имя_проекта>"
  exit 1
fi

TEMPLATE="$HOME/clion-templates/c-cpp-cython-python-universal"
DEST="$HOME/CLionProjects/$PROJECT_NAME"

cp -r "$TEMPLATE" "$DEST"

cd "$DEST" || exit 1

find . -type f -name "CMakeLists.txt.in" -exec sed -i "s/@PROJECT_NAME@/$PROJECT_NAME/g" {} \;
find . -type f -name "CMakeLists.txt.in" -exec mv {} $(dirname {})/CMakeLists.txt \;

find . -type f -name ".gitignore.template" -exec mv {} .gitignore \;

LIBRARIES_DIR="lib"
PYBIND11_DIR="$LIBRARIES_DIR/pybind11"
PYBIND11_REPO="https://github.com/pybind/pybind11.git"

echo "Инициализируем git для проекта..."
git init

if [ ! -d "$PYBIND11_DIR" ]; then
    echo "Добавляем pybind11 как git submodule в $PYBIND11_DIR..."
    git submodule add -f "$PYBIND11_REPO" "$PYBIND11_DIR"
    
    if [ $? -eq 0 ]; then
        echo "pybind11 успешно добавлен как submodule"
    else
        echo "Подмодуль уже существует или ошибка при добавлении"
    fi
else
    echo "📁 Папка $PYBIND11_DIR уже существует, пропускаем клонирование"
fi

git config core.fileMode false

echo "Создаём виртуальное окружение .venv..."
python3 -m venv .venv

if [ $? -ne 0 ]; then
    echo "Ошибка: не удалось создать .venv. Убедитесь, что установлен python3-venv"
    exit 1
fi

echo "Виртуальное окружение .venv создано"

echo "Активируем .venv и обновляем pip..."
source .venv/bin/activate
python -m pip install --upgrade pip

if [ $? -ne 0 ]; then
    echo "❌ Ошибка при обновлении pip"
    exit 1
fi

echo "pip обновлён"

echo "Устанавливаем основные пакеты: numpy, cython"
pip install numpy cython

if [ $? -eq 0 ]; then
    echo "numpy и cython установлены в .venv"
else
    echo "Ошибка при установке numpy/cython (необходимо установить вручную)"
fi

git add .
git commit -m "Initial commit from template with pybind11 submodule and .venv"

echo "Проект '$PROJECT_NAME' создан в $DEST, открой его в CLion"