FROM archlinux:latest

RUN sed -i '/NoExtract/d' /etc/pacman.conf && \
    pacman -Syu --noconfirm && \
    pacman -Sy --noconfirm \
        python \
        python-pip \
        git && \
    pip install --no-cache-dir --break-system-packages \
        sphinx \
        sphinx-rtd-theme && \
    pacman -Scc --noconfirm

WORKDIR /docs

COPY docs/python/conf.py docs/python/

CMD ["sh", "-c", "echo 'Используй: docker run --rm -v $(pwd):/docs docs-builder <команда>'; echo '  make -C docs/python html'"]
